# Copyright (c) 2026 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# CPUFLPR has limited RAM.

CONFIG_LOG=n
CONFIG_LOG_CMDS=n
CONFIG_KERNEL_SHELL=n
CONFIG_THREAD_MONITOR=n
CONFIG_THREAD_RUNTIME_STATS=n
CONFIG_STATS=n
CONFIG_STATS_SHELL=n
CONFIG_DEVICE_SHELL=n
CONFIG_INIT_STACKS=n
CONFIG_THREAD_STACK_INFO=n

CONFIG_PBUF_RX_READ_BUF_SIZE=128
CONFIG_IPC_SERVICE_BACKEND_ICMSG_WQ_STACK_SIZE=1024
