# nothing here
CONFIG_SHELL_CMD_BUFF_SIZE=2048
CONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=512
CONFIG_UART_136_A2I_RX_SIZE=128
CONFIG_SHELL=y
CONFIG_SHELL_DEFAULT_TERMINAL_WIDTH=1024
CONFIG_LOG=y
CONFIG_DCACHE=y
CONFIG_SHELL_ECHO_STATUS=n
CONFIG_OUTPUT_DISASSEMBLY=y
