# Copyright (c) 2026 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# Base configuration; snippet nordic-log-stm adds STM log frontend (see sample.yaml).

CONFIG_SOC_NRF54H20_CPURAD_ENABLE=y

CONFIG_PRINTK=y

CONFIG_IPC_SERVICE=y
CONFIG_PBUF_RX_READ_BUF_SIZE=256
CONFIG_MBOX=y

CONFIG_ASSERT=y

CONFIG_SHELL=y
CONFIG_SHELL_REMOTE=y
CONFIG_SHELL_STACK_SIZE=4096
CONFIG_SHELL_CMDS_SELECT=y
CONFIG_LOG_CMDS=y

# ETR shell integration conflicts with the main shell instance (see DEBUG_NRF_ETR_SHELL).
CONFIG_DEBUG_NRF_ETR_SHELL=n
